/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.utfpr.veiculos.interfaces;

import br.edu.utfpr.veiculos.Carga;
import br.edu.utfpr.veiculos.Repositorio;
import br.edu.utfpr.veiculos.VelocException;
import javax.swing.JOptionPane;

/**
 *
 * @author cazevedo
 */
public class CadastroCarga extends javax.swing.JFrame {
    private Carga veiculo;
    private static CadastroCarga cadastroCarga;

    /**
     * Creates new form CadastroCarga
     */
    private CadastroCarga() {
        initComponents();
        veiculo = new Carga();
    }
    
    public static CadastroCarga criaCadastroCarga() {
        if(cadastroCarga == null) cadastroCarga = new CadastroCarga();
        
        return cadastroCarga;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTara = new javax.swing.JLabel();
        lblCargaMaxima = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        lblQuantidadeRodas = new javax.swing.JLabel();
        lblVelocidadeMaxima = new javax.swing.JLabel();
        lblQuantidadePistoes = new javax.swing.JLabel();
        lblPotencia = new javax.swing.JLabel();
        btnSairCadastroCarga = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtQuantidadePistoes = new javax.swing.JTextField();
        txtTara = new javax.swing.JTextField();
        txtPotencia = new javax.swing.JTextField();
        txtCargaMaxima = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        txtQuantidadeRodas = new javax.swing.JTextField();
        txtVelocidadeMaxima = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Carga");

        lblTara.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblTara.setText("Tara:");

        lblCargaMaxima.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblCargaMaxima.setText("Carga Máxima: ");

        lblPlaca.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblPlaca.setText("Placa:");

        lblMarca.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblMarca.setText("Marca:");

        lblModelo.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblModelo.setText("Modelo:");

        lblCor.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblCor.setText("Cor:");

        lblQuantidadeRodas.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblQuantidadeRodas.setText("Quantidade de Rodas: ");

        lblVelocidadeMaxima.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblVelocidadeMaxima.setText("Velocidade Máxima:");

        lblQuantidadePistoes.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblQuantidadePistoes.setText("Quantidade de Pistões:");

        lblPotencia.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblPotencia.setText("Potência:");

        btnSairCadastroCarga.setText("Sair");
        btnSairCadastroCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroCargaActionPerformed(evt);
            }
        });

        jButton2.setText("Novo");

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cadastrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlaca)
                    .addComponent(lblTara)
                    .addComponent(lblQuantidadePistoes)
                    .addComponent(lblVelocidadeMaxima)
                    .addComponent(lblQuantidadeRodas)
                    .addComponent(lblCor)
                    .addComponent(lblModelo)
                    .addComponent(lblMarca)
                    .addComponent(lblCargaMaxima)
                    .addComponent(lblPotencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTara, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidadePistoes, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidadeRodas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVelocidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSairCadastroCarga)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTara)
                    .addComponent(txtTara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargaMaxima)
                    .addComponent(txtCargaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeRodas)
                    .addComponent(txtQuantidadeRodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelocidadeMaxima)
                    .addComponent(txtVelocidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadePistoes)
                    .addComponent(txtQuantidadePistoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPotencia)
                    .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSairCadastroCarga)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cadastrarCarga();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limpar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSairCadastroCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroCargaActionPerformed
        sair();
    }//GEN-LAST:event_btnSairCadastroCargaActionPerformed

    private void limpar() {
        txtTara.setText("");
        txtCargaMaxima.setText("");
        txtPlaca.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtCor.setText("");
        txtQuantidadeRodas.setText("");
        txtVelocidadeMaxima.setText("");
        txtPotencia.setText("");
        txtQuantidadePistoes.setText("");
        txtTara.requestFocus();
    }
    
    private void sair() {
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "saida", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (resposta == 0) {
            dispose();
        }
    }
    
    private void cadastrarCarga() {
        veiculo = new Carga();
        
        veiculo.setTara(Integer.parseInt(txtTara.getText()));
        veiculo.setCargaMaxima(Integer.parseInt(txtCargaMaxima.getText()));
        veiculo.setPlaca(txtPlaca.getText());
        veiculo.setMarca(txtMarca.getText());
        veiculo.setModelo(txtModelo.getText());
        veiculo.setCor(txtCor.getText());
        veiculo.setQuantidadeRodas(Integer.parseInt(txtQuantidadeRodas.getText()));
        try {
            veiculo.setVelocidadeMaxima(Float.parseFloat(txtVelocidadeMaxima.getText()));
        } catch (VelocException ve) {
            JOptionPane.showMessageDialog(null, "Velocidade fora dos padrões brasileiros.", "Erro!", JOptionPane.ERROR_MESSAGE);
            txtVelocidadeMaxima.requestFocus();
        }
        veiculo.getMotor().setQuantidadePistoes(Integer.parseInt(txtQuantidadePistoes.getText()));
        veiculo.getMotor().setPotencia(Integer.parseInt(txtPotencia.getText()));
        
        Carga resultado = (Carga) Repositorio.getRepositorio().inserir(veiculo);
        
        if (resultado != null) {
            JOptionPane.showMessageDialog(null, "Veículo " + resultado.getPlaca() + " cadastrado com sucesso!", "Cadastro efetuado", JOptionPane.INFORMATION_MESSAGE);
            limpar();
        } else {
            JOptionPane.showMessageDialog(null, "Veículo já cadastrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        /*
        System.out.println(veiculo.getTara());
        System.out.println(veiculo.getCargaMaxima());
        System.out.println(veiculo.getPlaca());
        System.out.println(veiculo.getMarca());
        System.out.println(veiculo.getModelo());
        System.out.println(veiculo.getCor());
        System.out.println(veiculo.getQuantidadeRodas());
        System.out.println(veiculo.getVelocidadeMaxima());
        System.out.println(veiculo.getMotor().getPotencia());
        System.out.println(veiculo.getMotor().getQuantidadePistoes());
        */
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSairCadastroCarga;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lblCargaMaxima;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPotencia;
    private javax.swing.JLabel lblQuantidadePistoes;
    private javax.swing.JLabel lblQuantidadeRodas;
    private javax.swing.JLabel lblTara;
    private javax.swing.JLabel lblVelocidadeMaxima;
    private javax.swing.JTextField txtCargaMaxima;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPotencia;
    private javax.swing.JTextField txtQuantidadePistoes;
    private javax.swing.JTextField txtQuantidadeRodas;
    private javax.swing.JTextField txtTara;
    private javax.swing.JTextField txtVelocidadeMaxima;
    // End of variables declaration//GEN-END:variables
}
