/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.utfpr.veiculos.interfaces;

import br.edu.utfpr.veiculos.Passeio;
import br.edu.utfpr.veiculos.Repositorio;
import br.edu.utfpr.veiculos.VelocException;
import javax.swing.JOptionPane;

/**
 *
 * @author cazevedo
 */
public class CadastroPasseio extends javax.swing.JFrame {
    private Passeio veiculo;
    private static CadastroPasseio cadastroPasseio;

    /**
     * Creates new form CadastroPasseio
     */
    private CadastroPasseio() {
        initComponents();
        veiculo = new Passeio();
    }
    
    public static CadastroPasseio criaCadastroPasseio() {
        if(cadastroPasseio == null) {
            cadastroPasseio = new CadastroPasseio();
        }
        
        return cadastroPasseio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPotencia = new javax.swing.JLabel();
        btnSairCadastroPasseio = new javax.swing.JButton();
        txtModelo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lblQuantidadePassageiros = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtMarca = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblMarca = new javax.swing.JLabel();
        txtQuantidadePistoes = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtQuantidadeRodas = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtPotencia = new javax.swing.JTextField();
        lblQuantidadeRodas = new javax.swing.JLabel();
        txtQuantidadePassageiros = new javax.swing.JTextField();
        txtVelocidadeMaxima = new javax.swing.JTextField();
        lblVelocidadeMaxima = new javax.swing.JLabel();
        lblQuantidadePistoes = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Veiculos Passeio");

        lblPotencia.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblPotencia.setText("Potência:");

        btnSairCadastroPasseio.setText("Sair");
        btnSairCadastroPasseio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroPasseioActionPerformed(evt);
            }
        });

        jButton2.setText("Novo");

        lblQuantidadePassageiros.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblQuantidadePassageiros.setText("Quantidade de Passageiros:");

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblPlaca.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblPlaca.setText("Placa:");

        jButton4.setText("Cadastrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblMarca.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblMarca.setText("Marca:");

        lblModelo.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblModelo.setText("Modelo:");

        lblCor.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblCor.setText("Cor:");

        lblQuantidadeRodas.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblQuantidadeRodas.setText("Quantidade de Rodas: ");

        lblVelocidadeMaxima.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblVelocidadeMaxima.setText("Velocidade Máxima:");

        lblQuantidadePistoes.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblQuantidadePistoes.setText("Quantidade de Pistões:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVelocidadeMaxima)
                        .addGap(60, 60, 60)
                        .addComponent(txtVelocidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuantidadePistoes)
                        .addGap(40, 40, 40)
                        .addComponent(txtQuantidadePistoes, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblModelo)
                        .addGap(137, 137, 137)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCor)
                        .addGap(162, 162, 162)
                        .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPotencia)
                        .addGap(128, 128, 128)
                        .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMarca)
                        .addGap(144, 144, 144)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuantidadeRodas)
                        .addGap(44, 44, 44)
                        .addComponent(txtQuantidadeRodas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlaca)
                        .addGap(149, 149, 149)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuantidadePassageiros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuantidadePassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSairCadastroPasseio)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadePassageiros)
                    .addComponent(txtQuantidadePassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeRodas)
                    .addComponent(txtQuantidadeRodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelocidadeMaxima)
                    .addComponent(txtVelocidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadePistoes)
                    .addComponent(txtQuantidadePistoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPotencia)
                    .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSairCadastroPasseio)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairCadastroPasseioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroPasseioActionPerformed
        sair();
    }//GEN-LAST:event_btnSairCadastroPasseioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limpar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cadastrarPasseio();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void sair() {
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "saida", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (resposta == 0) {
            dispose();
        }
    }
    
    private void limpar() {
        txtQuantidadePassageiros.setText("");
        txtPlaca.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtCor.setText("");
        txtQuantidadeRodas.setText("");
        txtVelocidadeMaxima.setText("");
        txtPotencia.setText("");
        txtQuantidadePistoes.setText("");
        txtQuantidadePassageiros.requestFocus();
    }
    
    private void cadastrarPasseio() {
        veiculo = new Passeio();
        Boolean erro = false;
        
        veiculo.setQuantidadePassageiros(Integer.parseInt(txtQuantidadePassageiros.getText()));
        veiculo.setPlaca(txtPlaca.getText());
        veiculo.setMarca(txtMarca.getText());
        veiculo.setModelo(txtModelo.getText());
        veiculo.setCor(txtCor.getText());
        veiculo.setQuantidadeRodas(Integer.parseInt(txtQuantidadeRodas.getText()));
        try {
            veiculo.setVelocidadeMaxima(Float.parseFloat(txtVelocidadeMaxima.getText()));
        } catch (VelocException ve) {
            JOptionPane.showMessageDialog(null, "Velocidade fora dos padrões brasileiros.", "Erro!", JOptionPane.ERROR_MESSAGE);
            txtVelocidadeMaxima.requestFocus();
            erro = true;
        }
        veiculo.getMotor().setQuantidadePistoes(Integer.parseInt(txtQuantidadePistoes.getText()));
        veiculo.getMotor().setPotencia(Integer.parseInt(txtPotencia.getText()));
        
        if (!erro) {
            Passeio resultado = (Passeio) Repositorio.getRepositorio().inserir(veiculo);
        
            if (resultado != null) {
                JOptionPane.showMessageDialog(null, "Veículo " + resultado.getPlaca() + " cadastrado com sucesso!", "Cadastro efetuado", JOptionPane.INFORMATION_MESSAGE);
                limpar();
            } else {
                JOptionPane.showMessageDialog(null, "Veículo já cadastrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPasseio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSairCadastroPasseio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPotencia;
    private javax.swing.JLabel lblQuantidadePassageiros;
    private javax.swing.JLabel lblQuantidadePistoes;
    private javax.swing.JLabel lblQuantidadeRodas;
    private javax.swing.JLabel lblVelocidadeMaxima;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPotencia;
    private javax.swing.JTextField txtQuantidadePassageiros;
    private javax.swing.JTextField txtQuantidadePistoes;
    private javax.swing.JTextField txtQuantidadeRodas;
    private javax.swing.JTextField txtVelocidadeMaxima;
    // End of variables declaration//GEN-END:variables
}
