/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.utfpr.veiculos.interfaces;

import br.edu.utfpr.veiculos.Passeio;
import br.edu.utfpr.veiculos.Repositorio;
import javax.swing.JOptionPane;

/**
 *
 * @author cazevedo
 */
public class ConsultaPasseio extends javax.swing.JFrame {
    private Passeio veiculo;
    private static ConsultaPasseio consultaPasseio;

    /**
     * Creates new form ConsultaPasseio
     */
    private ConsultaPasseio() {
        initComponents();
        veiculo = new Passeio();
        txtPlaca.requestFocus();
    }

    public static ConsultaPasseio criaConsultaPasseio() {
        if (consultaPasseio == null) consultaPasseio = new ConsultaPasseio();
        
        return consultaPasseio;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPotencia = new javax.swing.JLabel();
        btnSairCadastroPasseio = new javax.swing.JButton();
        txtModelo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lblCargaMaxima = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblMarca = new javax.swing.JLabel();
        txtQuantidadePistoes = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtQuantidadeRodas = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtPotencia = new javax.swing.JTextField();
        lblQuantidadeRodas = new javax.swing.JLabel();
        txtQuantidadePassageiros = new javax.swing.JTextField();
        txtVelocidadeMaxima = new javax.swing.JTextField();
        lblVelocidadeMaxima = new javax.swing.JLabel();
        lblQuantidadePistoes = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPotencia.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblPotencia.setText("Potência:");

        btnSairCadastroPasseio.setText("Sair");
        btnSairCadastroPasseio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroPasseioActionPerformed(evt);
            }
        });

        txtModelo.setEditable(false);

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblCargaMaxima.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblCargaMaxima.setText("Quantidade de Passageiros: ");

        txtMarca.setEditable(false);

        lblPlaca.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblPlaca.setText("Placa:");

        jButton4.setText("Consultar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblMarca.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblMarca.setText("Marca:");

        txtQuantidadePistoes.setEditable(false);

        txtCor.setEditable(false);

        lblModelo.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblModelo.setText("Modelo:");

        txtQuantidadeRodas.setEditable(false);

        lblCor.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblCor.setText("Cor:");

        txtPotencia.setEditable(false);

        lblQuantidadeRodas.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblQuantidadeRodas.setText("Quantidade de Rodas: ");

        txtQuantidadePassageiros.setEditable(false);

        txtVelocidadeMaxima.setEditable(false);

        lblVelocidadeMaxima.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblVelocidadeMaxima.setText("Velocidade Máxima:");

        lblQuantidadePistoes.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblQuantidadePistoes.setText("Quantidade de Pistões:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlaca)
                    .addComponent(lblQuantidadePistoes)
                    .addComponent(lblVelocidadeMaxima)
                    .addComponent(lblQuantidadeRodas)
                    .addComponent(lblCor)
                    .addComponent(lblModelo)
                    .addComponent(lblMarca)
                    .addComponent(lblCargaMaxima)
                    .addComponent(lblPotencia)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidadePistoes, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidadePassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidadeRodas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVelocidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSairCadastroPasseio)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargaMaxima)
                    .addComponent(txtQuantidadePassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeRodas)
                    .addComponent(txtQuantidadeRodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelocidadeMaxima)
                    .addComponent(txtVelocidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadePistoes)
                    .addComponent(txtQuantidadePistoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPotencia)
                    .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSairCadastroPasseio)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairCadastroPasseioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroPasseioActionPerformed
        sair();
    }//GEN-LAST:event_btnSairCadastroPasseioActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        consultarPasseio();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        excluiPassageiro();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void consultarPasseio() {
        veiculo = new Passeio();
        
        veiculo.setPlaca(txtPlaca.getText());
        
        veiculo = (Passeio) Repositorio.getRepositorio().pesquisar(veiculo);
        
        if (veiculo != null) {
            txtQuantidadePassageiros.setText(Integer.toString(veiculo.getQuantidadePassageiros()));
            txtPlaca.setText(veiculo.getPlaca());
            txtMarca.setText(veiculo.getMarca());
            txtModelo.setText(veiculo.getModelo());
            txtCor.setText(veiculo.getCor());
            txtQuantidadeRodas.setText(Integer.toString(veiculo.getQuantidadeRodas()));
            txtVelocidadeMaxima.setText(Float.toString(veiculo.getVelocidadeMaxima()));
            txtPotencia.setText(Integer.toString(veiculo.getMotor().getPotencia()));
            txtQuantidadePistoes.setText(Integer.toString(veiculo.getMotor().getQuantidadePistoes()));
            JOptionPane.showMessageDialog(null, "Veiculo encontrado!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Veículo não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void sair() {
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "saida", JOptionPane.YES_NO_CANCEL_OPTION);

        if (resposta == 0) {
            dispose();
        }
    }
    
    private void limpar() {
        txtQuantidadePassageiros.setText("");
        txtPlaca.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtCor.setText("");
        txtQuantidadeRodas.setText("");
        txtVelocidadeMaxima.setText("");
        txtPotencia.setText("");
        txtQuantidadePistoes.setText("");
        txtPlaca.requestFocus();
    }
    
    private void excluiPassageiro() {
        veiculo = new Passeio();
        
        veiculo.setPlaca(txtPlaca.getText());
        
        veiculo = (Passeio) Repositorio.getRepositorio().excluir(veiculo);
        
        if (veiculo == null) {
            limpar();
            JOptionPane.showMessageDialog(null, "Veiculo excluído!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Veículo não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            txtPlaca.requestFocus();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPasseio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSairCadastroPasseio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lblCargaMaxima;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPotencia;
    private javax.swing.JLabel lblQuantidadePistoes;
    private javax.swing.JLabel lblQuantidadeRodas;
    private javax.swing.JLabel lblVelocidadeMaxima;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPotencia;
    private javax.swing.JTextField txtQuantidadePassageiros;
    private javax.swing.JTextField txtQuantidadePistoes;
    private javax.swing.JTextField txtQuantidadeRodas;
    private javax.swing.JTextField txtVelocidadeMaxima;
    // End of variables declaration//GEN-END:variables
}
