/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.utfpr.veiculos.interfaces;

import br.edu.utfpr.veiculos.Passeio;
import br.edu.utfpr.veiculos.Repositorio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cazevedo
 */
public class ListaPasseio extends javax.swing.JFrame {
    private static ListaPasseio listaPasseio;

    /**
     * Creates new form ListaPasseio
     */
    private ListaPasseio() {
        initComponents();
        atualizaTabela();
    }
    
    public static ListaPasseio criaListaPasseio() {
        if (listaPasseio == null) {
            listaPasseio = new ListaPasseio();
        }
        
        return listaPasseio;
    }
    
    public void atualizaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tblPasseio.getModel();
        
        int linha = 0;
        modelo.setRowCount(linha);
        
        for(Passeio veiculo : Repositorio.getVeiculosPasseio()) {
            modelo.insertRow(linha++, new Object[] {
                veiculo.getPlaca(),
                veiculo.getMarca(),
                veiculo.getModelo(),
                veiculo.getCor(),
                veiculo.getQuantidadeRodas(),
                veiculo.getVelocidadeMaxima(),
                veiculo.getMotor().getQuantidadePistoes(),
                veiculo.getMotor().getPotencia(),
                veiculo.getQuantidadePassageiros()
            });
        }
    }
    
    private void sair() {
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "saida", JOptionPane.YES_NO_CANCEL_OPTION);

        if (resposta == 0) {
            listaPasseio = null;
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPasseio = new javax.swing.JTable();
        btnExcluirTodosPasseio = new javax.swing.JButton();
        btnSairListaPasseio = new javax.swing.JButton();
        btnImprimirTodosPasseio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Imprimir / Excluir todos");

        tblPasseio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo", "Cor", "Quantidade de Rodas", "Velocidade Máxima", "Quantidade Pistões", "Potência", "Quantidade de Passageiros"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPasseio);

        btnExcluirTodosPasseio.setText("Excluir todos");
        btnExcluirTodosPasseio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTodosPasseioActionPerformed(evt);
            }
        });

        btnSairListaPasseio.setText("Sair");
        btnSairListaPasseio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairListaPasseioActionPerformed(evt);
            }
        });

        btnImprimirTodosPasseio.setText("Imprimir todos");
        btnImprimirTodosPasseio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirTodosPasseioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImprimirTodosPasseio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirTodosPasseio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSairListaPasseio))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirTodosPasseio)
                    .addComponent(btnSairListaPasseio)
                    .addComponent(btnImprimirTodosPasseio))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairListaPasseioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairListaPasseioActionPerformed
        sair();
    }//GEN-LAST:event_btnSairListaPasseioActionPerformed

    private void btnExcluirTodosPasseioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTodosPasseioActionPerformed
        // TODO add your handling code here:
        Repositorio.getRepositorio().excluiTodosPasseio();
        JOptionPane.showMessageDialog(null, "Veiculos de passeio excluidos!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        atualizaTabela();
    }//GEN-LAST:event_btnExcluirTodosPasseioActionPerformed

    private void btnImprimirTodosPasseioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirTodosPasseioActionPerformed
        // TODO add your handling code here:
        atualizaTabela();
    }//GEN-LAST:event_btnImprimirTodosPasseioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPasseio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPasseio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirTodosPasseio;
    private javax.swing.JButton btnImprimirTodosPasseio;
    private javax.swing.JButton btnSairListaPasseio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPasseio;
    // End of variables declaration//GEN-END:variables
}
