/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.utfpr.veiculos.interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author cazevedo
 */
public class MenuCarga extends javax.swing.JFrame {
    private static MenuCarga menuCarga;

    /**
     * Creates new form MenuCarga
     */
    private MenuCarga() {
        initComponents();
    }
    
    public static MenuCarga criaMenuCarga() {
        if(menuCarga == null) menuCarga = new MenuCarga();
        
        return menuCarga;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarCarga = new javax.swing.JButton();
        btnConsultarCarga = new javax.swing.JButton();
        btnImprimirCarga = new javax.swing.JButton();
        btnSairCarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Veículos de Carga");

        btnCadastrarCarga.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        btnCadastrarCarga.setText("Cadastrar");
        btnCadastrarCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCargaActionPerformed(evt);
            }
        });

        btnConsultarCarga.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        btnConsultarCarga.setText("Consultar / Excluir pela placa");
        btnConsultarCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCargaActionPerformed(evt);
            }
        });

        btnImprimirCarga.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        btnImprimirCarga.setText("Imprimir / Excluir todos");
        btnImprimirCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirCargaActionPerformed(evt);
            }
        });

        btnSairCarga.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        btnSairCarga.setText("Sair");
        btnSairCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCadastrarCarga)
                    .addComponent(btnConsultarCarga)
                    .addComponent(btnImprimirCarga)
                    .addComponent(btnSairCarga))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnCadastrarCarga)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarCarga)
                .addGap(18, 18, 18)
                .addComponent(btnImprimirCarga)
                .addGap(18, 18, 18)
                .addComponent(btnSairCarga)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCargaActionPerformed
        CadastroCarga.criaCadastroCarga().setVisible(true);
    }//GEN-LAST:event_btnCadastrarCargaActionPerformed

    private void btnConsultarCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCargaActionPerformed
        ConsultaCarga.criaConsultaCarga().setVisible(true);
    }//GEN-LAST:event_btnConsultarCargaActionPerformed

    private void btnImprimirCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirCargaActionPerformed
        ListaCarga.criaListaCarga().setVisible(true);
    }//GEN-LAST:event_btnImprimirCargaActionPerformed

    private void btnSairCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCargaActionPerformed
        sair();
    }//GEN-LAST:event_btnSairCargaActionPerformed

    private void sair() {
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "saida", JOptionPane.YES_NO_CANCEL_OPTION);

        if (resposta == 0) {
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCarga;
    private javax.swing.JButton btnConsultarCarga;
    private javax.swing.JButton btnImprimirCarga;
    private javax.swing.JButton btnSairCarga;
    // End of variables declaration//GEN-END:variables
}
